server:
  port: 9081

spring:
  cloud:
    schema-registry-client:
      endpoint: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true # \ both event-service and user-service can create topic and add partitions
          min-partition-count: 3    # /
      bindings:
        users-in-0:
          destination: com.spring.kafka.avro.newuser
          content-type: application/*+avro
          group: eventServiceGroup
          consumer:
            use-native-encoding: true
            ack-mode: RECORD # setting it explicitly as suggest in https://githubmemory.com/repo/spring-cloud/spring-cloud-stream-binder-kafka/issues/1079


management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always
